# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: Default

steps:

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
    
- task: FortifyScanCentralSAST@7
  inputs:
    scanCentralCtrlUrl: 'http://10.229.222.183:8999/scancentral-ctrl/'
    scanCentralClientToken: '$(ScanCentral.ClientToken)'
    sscUrl: 'http://10.229.222.183:8180/ssc'
    sscCiToken: '$(ScanCentral.SscCiToken)'
    uploadToSSC: true
    applicationName: 'Petstore'
    applicationVersion: 'v1'
    #buildFailureCriteria: '[fortify priority order]:critical'
    timeoutForPollingArtifactState: 60
    buildTool: 'mvn'
    buildFile: 'pom.xml'
    block: true
    outputFile: 'scan.fpr'
    overwrite: true
    
- task: FortifyScanCentralDAST@7
  inputs:
    scanCentralDastApiUrl: 'http://10.229.222.165:8500/api/'
    scanCentralCiCdToken: '6c4fc9e1-e7a2-4c75-9459-6f9ac48a37f9'
    sscCiToken: '$(ScanCentral.SscCiToken)'